### PR TITLE
HTML math

### PR DESCRIPTION
**Pull request by encukou**
LaTex math isn't really used on naucse much, and the formula isn't that complex. Maybe we can postpone the whole LaTeX problem and just use standard HTML in the mean time. 

Thoughts?

### CODE REVIEW

**Comment by hroncok** [comment]
This definitely workarounds the problem. The question is, whether we want the ipytn render to Just Work™ or to make it Work Just Fine For Us™.

**Comment by encukou** [comment]
Yeah, it's a workaround, a way to merge stuff now and worry about TeX later.

Just an option, ignore it if you want.

**Comment by hroncok** [comment]
I'll think about it.

**Comment by hroncok** [comment]
Outdated, obsoleted, forgotten mostly.

**Pull request closed without merging**
